
services:
  api:
    build: .
    container_name: capture_os_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Mapeia a pasta data para que os vídeos/json locais persistam durante o dev
      - ./data:/app/data
      # Carrega o .env automaticamente
      - ./.env:/app/.env
    environment:
      - BACKEND_URL=https://api.nomadelabs.com.br
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n-traefik_app_network"
      - "traefik.http.routers.captureos.entrypoints=websecure"
      - "traefik.http.routers.captureos.rule=Host(`api.nomadelabs.com.br`)"
      - "traefik.http.routers.captureos.tls.certresolver=le"
      - "traefik.http.services.captureos.loadbalancer.server.port=8000"
    networks:
      - default
      - n8n-traefik_app_network

networks:
  n8n-traefik_app_network:
    external: true
